
#  cos550-aimeelramirez-api

## Questions Collection [/api]


### Post to API [POST]

+ Request (application/json)

           {
               "prompt": "In a NABRE bible religious belief, is God real? Provide a verse from NABRE."
           }
