color: true
reporter: apiary
custom:
  apiaryApiKey: f53ff37b19b22861b30c2f88f376793a
  apiaryApiName: cos550aimeelramirezapi
dry-run: null
hookfiles: null
language: nodejs
require: null
server: npm start
server-wait: 3
init: false
names: false
only: []
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooks-worker-timeout: 5000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml
blueprint: apiary.apib
endpoint: 'https://cos550-aimeelramirez-api.herokuapp.com'
HOST: 'https://cos550-aimeelramirez-api.herokuapp.com'

